### ISSUE TITLE
Doesn't load webui: unauthorized

### ISSUE THREAD

**Issue by zilexa** [emmercm/docker-qbittorrent#104]
Ubuntu 20.10 host, using your compose. 

```
  qbittorrent-em:
    image: emmercm/qbittorrent:latest
    container_name: qbittorrent-em
    restart: always
    environment:
      TZ: $TZ
    volumes:
      - $DOCKERDIR/qbittorrent-em/config:/config
      - $DATAPOOL/Media/incoming:/Media/incoming
      - $DOCKERDIR/qbittorrent-em/data:/data
    ports:
      - 8080:8080
      - 6881:6881
      #- 6881:6881/udp
```

When I go to my localip:8080 I only see the text "unauthorized". 
I made sure the /config and /data dir have full rights and owned by the user, not root. 
The log (via portainer) does not give any hints: 
```
      

Waiting for internet connection ...



********************************


*                              *


*   External IP:(removed)  *


*                              *


********************************




******** Information ********


To control qBittorrent, access the Web UI at http://localhost:8080
``` 

I also tried the Linuxserver version, it's 360MB versus your 150MB image, but it does work. Luckily it has a environmental variable to change the internal webUI port.  

I would prefer to use your image, but I do not understand why it does not work.
