### ISSUE TITLE
Restart after add torrent file

### ISSUE THREAD

**Issue by a1ekseev** [emmercm/docker-qbittorrent#134]
Hi!
I add a torrent file, the download starts, then the container starts restarting all the time.
In the log:
```log
(N) 2022-02-23T19:50:39 - qBittorrent v4.4.1 started
(N) 2022-02-23T19:50:39 - Using config directory: /root/.config/qBittorrent
(I) 2022-02-23T19:50:39 - Trying to listen on: 0.0.0.0:6881,[::]:6881
(N) 2022-02-23T19:50:39 - Peer ID: -qB4410-
(N) 2022-02-23T19:50:39 - HTTP User-Agent is 'qBittorrent/4.4.1'
(I) 2022-02-23T19:50:39 - DHT support [ON]
(I) 2022-02-23T19:50:39 - Local Peer Discovery support [ON]
(I) 2022-02-23T19:50:39 - PeX support [ON]
(I) 2022-02-23T19:50:39 - Anonymous mode [OFF]
(I) 2022-02-23T19:50:39 - Encryption support [ON]
(I) 2022-02-23T19:50:39 - UPnP / NAT-PMP support [ON]
(W) 2022-02-23T19:50:39 - Couldn't load IP geolocation database. Reason: No such file or directory
(N) 2022-02-23T19:50:39 - Using built-in Web UI.
(W) 2022-02-23T19:50:39 - Couldn't load Web UI translation for selected locale (C).
(N) 2022-02-23T19:50:39 - Web UI: Now listening on IP: *, port: 8080
(I) 2022-02-23T19:50:39 - Successfully listening on IP: 127.0.0.1, port: TCP/6881
(I) 2022-02-23T19:50:39 - Successfully listening on IP: 127.0.0.1, port: UTP/6881
(I) 2022-02-23T19:50:39 - Successfully listening on IP: 172.21.0.2, port: TCP/6881
(I) 2022-02-23T19:50:39 - Successfully listening on IP: 172.21.0.2, port: UTP/6881
(I) 2022-02-23T19:50:39 - Detected external IP: 37.145.191.159
(I) 2022-02-23T19:50:40 - IP geolocation database loaded. Type: DBIP-Country-Lite. Build time: Tue Feb 1 01:11:03 2022.
(I) 2022-02-23T19:50:40 - Successfully updated IP geolocation database.
(N) 2022-02-23T19:50:45 - WebAPI login success. IP: ::ffff:172.21.0.9
(N) 2022-02-23T19:50:51 - 'my_file_name' added to download list.
(N) 2022-02-23T19:50:53 - qBittorrent v4.4.1 started
(N) 2022-02-23T19:50:53 - Using config directory: /root/.config/qBittorrent
(I) 2022-02-23T19:50:53 - Trying to listen on: 0.0.0.0:6881,[::]:6881
(N) 2022-02-23T19:50:53 - Peer ID: -qB4410-
(N) 2022-02-23T19:50:53 - HTTP User-Agent is 'qBittorrent/4.4.1'
(I) 2022-02-23T19:50:53 - DHT support [ON]
(I) 2022-02-23T19:50:53 - Local Peer Discovery support [ON]
(I) 2022-02-23T19:50:53 - PeX support [ON]
(I) 2022-02-23T19:50:53 - Anonymous mode [OFF]
(I) 2022-02-23T19:50:53 - Encryption support [ON]
(I) 2022-02-23T19:50:53 - UPnP / NAT-PMP support [ON]
(I) 2022-02-23T19:50:53 - IP geolocation database loaded. Type: DBIP-Country-Lite. Build time: Tue Feb 1 01:11:03 2022.
(N) 2022-02-23T19:50:53 - Using built-in Web UI.
(W) 2022-02-23T19:50:53 - Couldn't load Web UI translation for selected locale (C).
(N) 2022-02-23T19:50:53 - Web UI: Now listening on IP: *, port: 8080
(I) 2022-02-23T19:50:53 - Successfully listening on IP: 127.0.0.1, port: TCP/6881
(I) 2022-02-23T19:50:53 - Successfully listening on IP: 127.0.0.1, port: UTP/6881
(I) 2022-02-23T19:50:53 - Successfully listening on IP: 172.21.0.2, port: TCP/6881
(I) 2022-02-23T19:50:53 - Successfully listening on IP: 172.21.0.2, port: UTP/6881
(N) 2022-02-23T19:50:53 - 'my_file_name' restored.
(I) 2022-02-23T19:50:53 - Detected external IP: 37.145.191.159
(N) 2022-02-23T19:50:57 - qBittorrent v4.4.1 started
(N) 2022-02-23T19:50:57 - Using config directory: /root/.config/qBittorrent
(I) 2022-02-23T19:50:57 - Trying to listen on: 0.0.0.0:6881,[::]:6881
(N) 2022-02-23T19:50:57 - Peer ID: -qB4410-
(N) 2022-02-23T19:50:57 - HTTP User-Agent is 'qBittorrent/4.4.1'
(I) 2022-02-23T19:50:57 - DHT support [ON]
(I) 2022-02-23T19:50:57 - Local Peer Discovery support [ON]
(I) 2022-02-23T19:50:57 - PeX support [ON]
(I) 2022-02-23T19:50:57 - Anonymous mode [OFF]
(I) 2022-02-23T19:50:57 - Encryption support [ON]
(I) 2022-02-23T19:50:57 - UPnP / NAT-PMP support [ON]
(I) 2022-02-23T19:50:57 - IP geolocation database loaded. Type: DBIP-Country-Lite. Build time: Tue Feb 1 01:11:03 2022.
(N) 2022-02-23T19:50:57 - Using built-in Web UI.
(W) 2022-02-23T19:50:57 - Couldn't load Web UI translation for selected locale (C).
(N) 2022-02-23T19:50:57 - Web UI: Now listening on IP: *, port: 8080
(I) 2022-02-23T19:50:57 - Successfully listening on IP: 127.0.0.1, port: TCP/6881
(I) 2022-02-23T19:50:57 - Successfully listening on IP: 127.0.0.1, port: UTP/6881
(I) 2022-02-23T19:50:57 - Successfully listening on IP: 172.21.0.2, port: TCP/6881
(I) 2022-02-23T19:50:57 - Successfully listening on IP: 172.21.0.2, port: UTP/6881
(N) 2022-02-23T19:50:57 - 'my_file_name' restored.
(I) 2022-02-23T19:50:57 - Detected external IP: 37.145.191.159
```

docker-compose.yml

```yml
services:
  qbittorrent:
    image: emmercm/qbittorrent:4-alpine
    container_name: qbittorrent
    restart: unless-stopped
    volumes:
      - ./qbittorrent/config:/config
      - ./qbittorrent/data:/data
      - ./qbittorrent/downloads:/downloads
      - ./qbittorrent/incomplete:/incomplete
      - ./qbittorrent/watch:/watch
    ports:
      - 10.10.10.10:8080:8080/tcp
      - 10.10.10.10:6881:6881/tcp
      - 10.10.10.10:6881:6881/udp
    networks:
      app_home_network:
        ipv4_address: 172.21.0.2
```
